#!/bin/bash
# =============================================================================
# Deals — DigitalOcean droplet bootstrap + update
#
# First-time on a fresh Ubuntu droplet (as root or with sudo):
#   git clone https://github.com/madhu2456/deals.git /opt/deals
#   cd /opt/deals && chmod +x deploy.sh docker/entrypoint.sh && ./deploy.sh
#
# Later updates (also used by GitHub Actions over SSH):
#   cd /opt/deals && ./deploy.sh --update
# =============================================================================

set -euo pipefail

APP_NAME="deals"
APP_DIR="${APP_DIR:-/opt/deals}"
REPO_URL="${REPO_URL:-https://github.com/madhu2456/deals.git}"
BRANCH="${BRANCH:-main}"
DOMAIN="${DOMAIN:-deals.madhudadi.in}"
APP_PORT="${APP_PORT:-3000}"

MODE="bootstrap"
if [ "${1:-}" = "--update" ] || [ "${1:-}" = "update" ]; then
  MODE="update"
fi

echo "=== Deals deployment (${MODE}) ==="
echo "    APP_DIR=${APP_DIR}"
echo "    DOMAIN=${DOMAIN}"
echo "    BRANCH=${BRANCH}"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
need_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root (or via sudo)."
    exit 1
  fi
}

install_docker() {
  if ! command -v docker &>/dev/null; then
    echo "Installing Docker..."
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sh /tmp/get-docker.sh
    rm -f /tmp/get-docker.sh
    systemctl enable --now docker
  else
    echo "Docker already installed."
  fi

  if ! docker compose version &>/dev/null; then
    echo "Installing Docker Compose plugin..."
    apt-get update -y
    apt-get install -y docker-compose-plugin
  fi
}

ensure_env() {
  if [ ! -f "${APP_DIR}/.env" ]; then
    echo "Creating .env with secure defaults..."
    ADMIN_SECRET="$(openssl rand -hex 32)"
    ADMIN_PASSWORD="$(openssl rand -hex 12)"
    cat >"${APP_DIR}/.env" <<EOF
# Generated by deploy.sh — change ADMIN_* after first login
DATABASE_URL="file:/app/data/deals.db"
ADMIN_USERNAME="admin"
ADMIN_PASSWORD="${ADMIN_PASSWORD}"
ADMIN_SECRET="${ADMIN_SECRET}"
NEXT_PUBLIC_SITE_URL="https://${DOMAIN}"
APP_PORT=${APP_PORT}
RUN_SEED=true
NODE_ENV=production
EOF
    chmod 600 "${APP_DIR}/.env"
    echo "  .env written. Initial admin password: ${ADMIN_PASSWORD}"
    echo "  (also saved in ${APP_DIR}/.env — rotate after first login)"
  else
    echo ".env already exists — leaving it unchanged."
  fi
}

configure_nginx() {
  echo "Configuring Nginx reverse proxy for ${DOMAIN}..."
  apt-get update -y
  apt-get install -y nginx

  cat >"/etc/nginx/sites-available/${APP_NAME}" <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};

    client_max_body_size 10m;

    location / {
        proxy_pass http://127.0.0.1:${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }
}
EOF

  ln -sf "/etc/nginx/sites-available/${APP_NAME}" "/etc/nginx/sites-enabled/${APP_NAME}"
  rm -f /etc/nginx/sites-enabled/default
  nginx -t
  systemctl enable --now nginx
  systemctl reload nginx
}

pull_or_clone() {
  mkdir -p "${APP_DIR}"
  if [ -d "${APP_DIR}/.git" ]; then
    echo "Updating repository..."
    git -C "${APP_DIR}" fetch origin
    git -C "${APP_DIR}" checkout "${BRANCH}"
    git -C "${APP_DIR}" pull --ff-only origin "${BRANCH}"
  else
    # If directory has only deploy leftovers, clone into it
    if [ -z "$(ls -A "${APP_DIR}" 2>/dev/null | grep -v '^\.env$' || true)" ]; then
      echo "Cloning ${REPO_URL}..."
      git clone --branch "${BRANCH}" "${REPO_URL}" "${APP_DIR}"
    else
      echo "Cloning into temp then merging..."
      TMP="$(mktemp -d)"
      git clone --branch "${BRANCH}" "${REPO_URL}" "${TMP}"
      # Preserve .env
      if [ -f "${APP_DIR}/.env" ]; then
        cp "${APP_DIR}/.env" "${TMP}/.env"
      fi
      rm -rf "${APP_DIR}"
      mv "${TMP}" "${APP_DIR}"
    fi
  fi
}

compose_up() {
  cd "${APP_DIR}"
  echo "Building and starting containers..."
  docker compose pull 2>/dev/null || true
  docker compose up -d --build --remove-orphans

  # After first successful seed, stop re-seeding on every boot
  if grep -q '^RUN_SEED=true' .env 2>/dev/null; then
    # Wait a bit for container to finish seed, then flip flag
    sleep 5
    sed -i 's/^RUN_SEED=true/RUN_SEED=false/' .env || true
    echo "  RUN_SEED set to false for future restarts."
  fi

  echo "Container status:"
  docker compose ps
}

# ---------------------------------------------------------------------------
# Update path (used by CI)
# ---------------------------------------------------------------------------
if [ "${MODE}" = "update" ]; then
  need_root
  if [ ! -d "${APP_DIR}/.git" ]; then
    echo "App not bootstrapped at ${APP_DIR}. Run without --update first."
    exit 1
  fi
  pull_or_clone
  ensure_env
  # Ensure deploy.sh stays executable after pull
  chmod +x "${APP_DIR}/deploy.sh" 2>/dev/null || true
  compose_up
  echo ""
  echo "=== Update complete ==="
  echo "  App:  https://${DOMAIN} (or http://$(curl -s --max-time 3 ifconfig.me 2>/dev/null || echo 'YOUR_IP'))"
  echo "  Logs: cd ${APP_DIR} && docker compose logs -f"
  exit 0
fi

# ---------------------------------------------------------------------------
# Full bootstrap
# ---------------------------------------------------------------------------
need_root

echo "1. Updating system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y
apt-get install -y git curl ca-certificates openssl ufw

echo "2. Installing Docker..."
install_docker

echo "3. Setting up application directory..."
pull_or_clone
chmod +x "${APP_DIR}/deploy.sh" 2>/dev/null || true
chmod +x "${APP_DIR}/docker/entrypoint.sh" 2>/dev/null || true

echo "4. Environment file..."
ensure_env

echo "5. Building and starting app..."
compose_up

echo "6. Nginx reverse proxy..."
configure_nginx

echo "7. Firewall (optional-friendly defaults)..."
if command -v ufw &>/dev/null; then
  ufw allow OpenSSH || true
  ufw allow 'Nginx Full' || true
  ufw --force enable || true
fi

echo ""
echo "=== Deployment complete ==="
echo "  HTTP:  http://${DOMAIN}  (point DNS A record to this droplet)"
echo "  Admin: http://${DOMAIN}/admin"
echo "  Logs:  cd ${APP_DIR} && docker compose logs -f"
echo ""
echo "  SSL (after DNS propagates):"
echo "    apt-get install -y certbot python3-certbot-nginx"
echo "    certbot --nginx -d ${DOMAIN} -d www.${DOMAIN}"
echo ""
echo "  GitHub Actions: set secrets DEPLOY_HOST, DEPLOY_USER, DEPLOY_SSH_KEY"
echo "  then push to ${BRANCH} — workflow runs: ./deploy.sh --update"
