#!/bin/bash
# =============================================================================
# Deals — server bootstrap + non-root updates (user: madhu)
#
# First-time bootstrap (once, as root):
#   export DEPLOY_USER=madhu
#   git clone https://github.com/madhu2456/deals.git /opt/deals
#   cd /opt/deals && chmod +x deploy.sh docker/entrypoint.sh
#   sudo ./deploy.sh
#
# Updates as madhu (GitHub Actions):
#   cd /opt/deals && ./deploy.sh --update
# =============================================================================

set -euo pipefail

APP_NAME="deals"
DEPLOY_USER="${DEPLOY_USER:-madhu}"
REPO_URL="${REPO_URL:-https://github.com/madhu2456/deals.git}"
BRANCH="${BRANCH:-main}"
DOMAIN="${DOMAIN:-deals.madhudadi.in}"
# Host port (localhost). Avoid clash with blog:3001 / enroller:8000
APP_PORT="${APP_PORT:-3002}"
# Always deploy from /opt/deals
APP_DIR="${APP_DIR:-/opt/deals}"

MODE="bootstrap"
if [ "${1:-}" = "--update" ] || [ "${1:-}" = "update" ]; then
  MODE="update"
fi

echo "=== Deals deployment (${MODE}) ==="
echo "    APP_DIR=${APP_DIR}"
echo "    DOMAIN=${DOMAIN}"
echo "    BRANCH=${BRANCH}"
echo "    USER=$(whoami) (target deploy user: ${DEPLOY_USER})"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
need_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "Bootstrap requires root once. Run: sudo $0"
    exit 1
  fi
}

need_docker() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "Docker is not installed. Run full bootstrap as root first: sudo ./deploy.sh"
    exit 1
  fi
  if ! docker info >/dev/null 2>&1; then
    echo "Cannot talk to Docker as $(whoami)."
    echo "Add user to docker group (as root):"
    echo "  usermod -aG docker ${DEPLOY_USER}"
    echo "  # then log out/in, or: newgrp docker"
    exit 1
  fi
  if ! docker compose version >/dev/null 2>&1; then
    echo "docker compose plugin missing. Install as root: apt-get install -y docker-compose-plugin"
    exit 1
  fi
}

install_docker() {
  if ! command -v docker &>/dev/null; then
    echo "Installing Docker..."
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sh /tmp/get-docker.sh
    rm -f /tmp/get-docker.sh
    systemctl enable --now docker
  else
    echo "Docker already installed."
  fi

  if ! docker compose version &>/dev/null; then
    echo "Installing Docker Compose plugin..."
    apt-get update -y
    apt-get install -y docker-compose-plugin
  fi
}

ensure_deploy_user() {
  if ! id "${DEPLOY_USER}" >/dev/null 2>&1; then
    echo "Creating user ${DEPLOY_USER}..."
    useradd -m -s /bin/bash "${DEPLOY_USER}"
  fi
  usermod -aG docker "${DEPLOY_USER}" || true
  # Passwordless docker is via group membership (not sudo)
  echo "User ${DEPLOY_USER} is in docker group."
}

ensure_env() {
  if [ ! -f "${APP_DIR}/.env" ]; then
    echo "Creating .env with secure defaults..."
    ADMIN_SECRET="$(openssl rand -hex 32)"
    ADMIN_PASSWORD="$(openssl rand -hex 12)"
    cat >"${APP_DIR}/.env" <<EOF
# Generated by deploy.sh — change ADMIN_* after first login
DATABASE_URL="file:/app/data/deals.db"
ADMIN_USERNAME="admin"
ADMIN_PASSWORD="${ADMIN_PASSWORD}"
ADMIN_SECRET="${ADMIN_SECRET}"
NEXT_PUBLIC_SITE_URL="https://${DOMAIN}"
APP_PORT=${APP_PORT}
RUN_SEED=true
NODE_ENV=production
EOF
    chmod 600 "${APP_DIR}/.env"
    if id "${DEPLOY_USER}" >/dev/null 2>&1; then
      chown "${DEPLOY_USER}:${DEPLOY_USER}" "${APP_DIR}/.env" 2>/dev/null || true
    fi
    echo "  .env written. Initial admin password: ${ADMIN_PASSWORD}"
    echo "  (also saved in ${APP_DIR}/.env — rotate after first login)"
  else
    echo ".env already exists — ensuring APP_PORT=${APP_PORT}"
    if grep -q '^APP_PORT=' "${APP_DIR}/.env" 2>/dev/null; then
      sed -i "s/^APP_PORT=.*/APP_PORT=${APP_PORT}/" "${APP_DIR}/.env"
    else
      echo "APP_PORT=${APP_PORT}" >>"${APP_DIR}/.env"
    fi
  fi
}

# Run a command as root if needed (root, or passwordless sudo)
as_root() {
  if [ "$(id -u)" -eq 0 ]; then
    "$@"
  elif command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
    sudo "$@"
  else
    return 1
  fi
}

# Install repo nginx config → /etc/nginx/sites-available/deals (every deploy)
# Source of truth: ${APP_DIR}/nginx/deals.conf or deals.ssl.conf
install_nginx_from_repo() {
  local dest="/etc/nginx/sites-available/${APP_NAME}"
  local enabled="/etc/nginx/sites-enabled/${APP_NAME}"
  local http_src="${APP_DIR}/nginx/deals.conf"
  local ssl_src="${APP_DIR}/nginx/deals.ssl.conf"
  local tmp
  tmp="$(mktemp)"

  if [ ! -f "${http_src}" ]; then
    echo "  Nginx: no ${http_src} in repo — skipping"
    return 0
  fi

  echo "Installing Nginx site from repo → ${dest} (port ${APP_PORT})"

  # Prefer SSL template when Let's Encrypt certs already exist
  if [ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ] && [ -f "${ssl_src}" ]; then
    echo "  Using SSL template (certs found for ${DOMAIN})"
    sed -e "s/__DOMAIN__/${DOMAIN}/g" -e "s/__APP_PORT__/${APP_PORT}/g" "${ssl_src}" >"${tmp}"
    # Drop ssl_dhparam line if file missing (avoids nginx -t failure)
    if [ ! -f /etc/letsencrypt/ssl-dhparams.pem ]; then
      sed -i '/ssl_dhparam/d' "${tmp}"
    fi
    if [ ! -f /etc/letsencrypt/options-ssl-nginx.conf ]; then
      sed -i '/options-ssl-nginx.conf/d' "${tmp}"
    fi
  else
    echo "  Using HTTP template"
    sed -e "s/__DOMAIN__/${DOMAIN}/g" -e "s/__APP_PORT__/${APP_PORT}/g" "${http_src}" >"${tmp}"
  fi

  if ! as_root cp "${tmp}" "${dest}"; then
    echo "  WARNING: cannot write ${dest} (need root or passwordless sudo)."
    echo "  Install once: sudo cp ${tmp} ${dest} && sudo ln -sfn ${dest} ${enabled} && sudo nginx -t && sudo systemctl reload nginx"
    echo "  Or allow madhu: echo '${DEPLOY_USER} ALL=(root) NOPASSWD: /usr/sbin/nginx, /bin/systemctl reload nginx, /bin/cp, /bin/ln' | sudo tee /etc/sudoers.d/deals-nginx"
    rm -f "${tmp}"
    return 0
  fi
  rm -f "${tmp}"

  as_root ln -sfn "${dest}" "${enabled}" || true
  as_root mkdir -p /var/www/html || true

  if as_root nginx -t; then
    as_root systemctl reload nginx || as_root service nginx reload || true
    echo "  Nginx reloaded with git config for ${DOMAIN} → 127.0.0.1:${APP_PORT}"
  else
    echo "  ERROR: nginx -t failed after installing ${dest}"
    return 1
  fi
}

configure_nginx() {
  echo "Configuring Nginx reverse proxy for ${DOMAIN}..."
  apt-get update -y
  apt-get install -y nginx
  install_nginx_from_repo
  systemctl enable --now nginx
}

pull_or_clone() {
  # Avoid "dubious ownership" when directory was created by another user
  git config --global --add safe.directory "${APP_DIR}" 2>/dev/null || true

  # If root left root-owned files, git pull fails for madhu ("Permission denied")
  if [ ! -w "${APP_DIR}/.git" ] || [ ! -w "${APP_DIR}" ]; then
    echo "WARNING: ${APP_DIR} not fully writable by $(whoami)."
    echo "  As root run: chown -R ${DEPLOY_USER}:${DEPLOY_USER} ${APP_DIR}"
  fi

  if [ -d "${APP_DIR}/.git" ]; then
    echo "Updating repository (hard reset to origin/${BRANCH})..."
    if ! git -C "${APP_DIR}" fetch origin; then
      echo "git fetch failed — check ownership of ${APP_DIR} (must be ${DEPLOY_USER})"
      exit 1
    fi
    git -C "${APP_DIR}" checkout "${BRANCH}"
    # Server must match GitHub; discard local edits (preserve .env via clean -e)
    if ! git -C "${APP_DIR}" reset --hard "origin/${BRANCH}"; then
      echo "git reset failed — often root-owned files under ${APP_DIR}."
      echo "  Fix once as root: chown -R ${DEPLOY_USER}:${DEPLOY_USER} ${APP_DIR}"
      exit 1
    fi
    git -C "${APP_DIR}" clean -fd -e .env -e data -e 'prisma/*.db' -e 'prisma/*.db-journal' || true
  else
    mkdir -p "$(dirname "${APP_DIR}")"
    if [ -d "${APP_DIR}" ] && [ -n "$(ls -A "${APP_DIR}" 2>/dev/null | grep -v '^\.env$' || true)" ]; then
      echo "Cloning into temp then merging..."
      TMP="$(mktemp -d)"
      git clone --branch "${BRANCH}" "${REPO_URL}" "${TMP}"
      if [ -f "${APP_DIR}/.env" ]; then
        cp "${APP_DIR}/.env" "${TMP}/.env"
      fi
      # Preserve data if any
      rm -rf "${APP_DIR}"
      mv "${TMP}" "${APP_DIR}"
    else
      echo "Cloning ${REPO_URL}..."
      git clone --branch "${BRANCH}" "${REPO_URL}" "${APP_DIR}"
    fi
  fi
}

compose_up() {
  cd "${APP_DIR}"
  echo "Building and starting containers..."

  # Stop previous stack / anything holding APP_PORT (default 3000)
  docker compose down --remove-orphans 2>/dev/null || true
  if command -v docker >/dev/null 2>&1; then
    # Stop other containers publishing the same host port
    for id in $(docker ps -q --filter "publish=${APP_PORT}" 2>/dev/null || true); do
      echo "  Stopping container on port ${APP_PORT}: ${id}"
      docker stop "${id}" >/dev/null 2>&1 || true
      docker rm "${id}" >/dev/null 2>&1 || true
    done
  fi
  # Last resort: free host process on the port (if any)
  if command -v fuser >/dev/null 2>&1; then
    fuser -k "${APP_PORT}/tcp" 2>/dev/null || true
  elif command -v lsof >/dev/null 2>&1; then
    lsof -ti ":${APP_PORT}" | xargs -r kill 2>/dev/null || true
  fi

  docker compose pull 2>/dev/null || true
  docker compose up -d --build --remove-orphans

  if [ -f .env ] && grep -q '^RUN_SEED=true' .env 2>/dev/null; then
    sleep 5
    sed -i 's/^RUN_SEED=true/RUN_SEED=false/' .env || true
    echo "  RUN_SEED set to false for future restarts."
  fi

  echo "Container status:"
  docker compose ps
}

fix_ownership() {
  if [ "$(id -u)" -eq 0 ] && id "${DEPLOY_USER}" >/dev/null 2>&1; then
    chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "${APP_DIR}"
    echo "Ownership of ${APP_DIR} → ${DEPLOY_USER}"
  fi
}

# ---------------------------------------------------------------------------
# Update path (non-root: run as madhu — NEVER requires root)
# ---------------------------------------------------------------------------
if [ "${MODE}" = "update" ]; then
  echo "    Running non-root update as $(whoami)..."
  need_docker

  if [ ! -d "${APP_DIR}/.git" ]; then
    echo "App not found at ${APP_DIR}."
    exit 1
  fi

  if [ ! -w "${APP_DIR}" ]; then
    echo "No write access to ${APP_DIR} as $(whoami)."
    echo "As root once: chown -R ${DEPLOY_USER}:${DEPLOY_USER} ${APP_DIR}"
    exit 1
  fi

  # Repo may already be pulled by CI; pull again is fine / no-op if up to date
  pull_or_clone
  ensure_env
  chmod +x "${APP_DIR}/deploy.sh" "${APP_DIR}/docker/entrypoint.sh" 2>/dev/null || true
  compose_up
  # Copy nginx/*.conf from this repo into sites-available on every deploy
  install_nginx_from_repo

  echo ""
  echo "=== Update complete ==="
  echo "  App:  https://${DOMAIN}  (upstream 127.0.0.1:${APP_PORT})"
  echo "  Logs: cd ${APP_DIR} && docker compose logs -f"
  exit 0
fi

# ---------------------------------------------------------------------------
# Full bootstrap (root once) — prepares madhu + /home/madhu/deals
# ---------------------------------------------------------------------------
need_root

echo "1. Updating system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y
apt-get install -y git curl ca-certificates openssl ufw

echo "2. Installing Docker..."
install_docker

echo "3. Ensuring deploy user (${DEPLOY_USER})..."
ensure_deploy_user

echo "4. Application directory ${APP_DIR}..."
# Ensure home exists
if [ ! -d "/home/${DEPLOY_USER}" ]; then
  mkdir -p "/home/${DEPLOY_USER}"
  chown "${DEPLOY_USER}:${DEPLOY_USER}" "/home/${DEPLOY_USER}"
fi
pull_or_clone
chmod +x "${APP_DIR}/deploy.sh" "${APP_DIR}/docker/entrypoint.sh" 2>/dev/null || true

echo "5. Environment file..."
ensure_env
fix_ownership

echo "6. Building and starting app (as ${DEPLOY_USER})..."
# Run compose as deploy user so containers are owned correctly
if [ "$(id -u)" -eq 0 ]; then
  su - "${DEPLOY_USER}" -c "cd '${APP_DIR}' && docker compose up -d --build --remove-orphans"
  # Flip seed flag if needed
  if [ -f "${APP_DIR}/.env" ] && grep -q '^RUN_SEED=true' "${APP_DIR}/.env"; then
    sleep 5
    sed -i 's/^RUN_SEED=true/RUN_SEED=false/' "${APP_DIR}/.env" || true
  fi
else
  compose_up
fi

echo "7. Nginx reverse proxy..."
configure_nginx

echo "8. Firewall..."
if command -v ufw &>/dev/null; then
  ufw allow OpenSSH || true
  ufw allow 'Nginx Full' || true
  ufw --force enable || true
fi

fix_ownership

echo ""
echo "=== Deployment complete ==="
echo "  HTTP:  http://${DOMAIN}"
echo "  App:   ${APP_DIR} (owner: ${DEPLOY_USER})"
echo "  Admin: http://${DOMAIN}/admin"
echo "  Logs:  su - ${DEPLOY_USER} -c 'cd ${APP_DIR} && docker compose logs -f'"
echo ""
echo "  SSL:"
echo "    apt-get install -y certbot python3-certbot-nginx"
echo "    certbot --nginx -d ${DOMAIN} -d www.${DOMAIN}"
echo ""
echo "  GitHub Actions secrets:"
echo "    DEPLOY_USER=madhu"
echo "    DEPLOY_PATH=${APP_DIR}"
echo "    DEPLOY_HOST=<server-ip>"
echo "    DEPLOY_SSH_KEY=<private key for madhu>"
