export const DEFAULT_CATEGORIES = [
  {
    name: "AI & Machine Learning",
    slug: "ai-and-machine-learning",
    description: "Discounts on AI writing, image generation, coding assistants, and ML tools.",
    icon: "sparkles",
    color: "#6366F1",
    sortOrder: 1,
  },
  {
    name: "Cloud & Hosting",
    slug: "cloud-and-hosting",
    description: "Web hosting, VPS, cloud credits, and domain deals.",
    icon: "cloud",
    color: "#0EA5E9",
    sortOrder: 2,
  },
  {
    name: "Design & Creative",
    slug: "design-and-creative",
    description: "Design tools, stock photos, video editors, and creative software.",
    icon: "palette",
    color: "#EC4899",
    sortOrder: 3,
  },
  {
    name: "Development Tools",
    slug: "development-tools",
    description: "IDEs, dev tools, APIs, testing platforms, and CI/CD deals.",
    icon: "code-2",
    color: "#8B5CF6",
    sortOrder: 4,
  },
  {
    name: "Productivity",
    slug: "productivity",
    description: "Note-taking apps, task managers, calendars, and workspace tools.",
    icon: "check-square",
    color: "#059669",
    sortOrder: 5,
  },
  {
    name: "Learning & Education",
    slug: "learning-and-education",
    description: "Online courses, tutoring, certifications, and learning platforms.",
    icon: "graduation-cap",
    color: "#F59E0B",
    sortOrder: 6,
  },
  {
    name: "Marketing & Growth",
    slug: "marketing-and-growth",
    description: "Email marketing, SEO, analytics, and advertising tools.",
    icon: "trending-up",
    color: "#EF4444",
    sortOrder: 7,
  },
  {
    name: "Security & Privacy",
    slug: "security-and-privacy",
    description: "VPNs, password managers, antivirus, and privacy services.",
    icon: "shield-check",
    color: "#14B8A6",
    sortOrder: 8,
  },
  {
    name: "Finance",
    slug: "finance",
    description: "Banking, investing, budgeting, and payment tool offers.",
    icon: "landmark",
    color: "#10B981",
    sortOrder: 9,
  },
  {
    name: "Shopping & Lifestyle",
    slug: "shopping-and-lifestyle",
    description: "Fashion, electronics, subscriptions, and everyday brands.",
    icon: "shopping-bag",
    color: "#F97316",
    sortOrder: 10,
  },
  {
    name: "Travel",
    slug: "travel",
    description: "Flights, hotels, travel gear, and transportation deals.",
    icon: "plane",
    color: "#3B82F6",
    sortOrder: 11,
  },
  {
    name: "Health & Wellness",
    slug: "health-and-wellness",
    description: "Fitness apps, mental health, nutrition, and wellness products.",
    icon: "heart-pulse",
    color: "#E11D48",
    sortOrder: 12,
  },
] as const;

export type CategorySlug = (typeof DEFAULT_CATEGORIES)[number]["slug"];
